// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Yoga = require("@ostera/reiki/lib/js/src/Yoga.bs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Style$Workshop = require("./Style.bs.js");

function withText(text) {
  return /* record */[
          /* node */Yoga.Node[/* create */0](/* record */[
                /* width */100,
                /* height */100,
                /* justify_content : Space_between */3,
                /* flex_direction : Row */2,
                /* align_items : Center */2
              ]),
          /* text */text
        ];
}

var component = ReasonReact.statelessComponent("Button");

function style(palette) {
  return ReactDOMRe.Style[/* combine */0](Style$Workshop.palette(palette), {
              cursor: "pointer"
            });
}

function make(node, mode, onClick, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("button", {
                          style: Style$Workshop.project(node, style(mode)),
                          onClick: onClick
                        }, children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var S = 0;

exports.S = S;
exports.withText = withText;
exports.component = component;
exports.style = style;
exports.make = make;
/* component Not a pure module */
