// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


function color(param) {
  switch (param) {
    case 0 : 
        return "#ffffff";
    case 1 : 
        return "#333333";
    case 2 : 
        return "#dd4b39";
    case 3 : 
        return "#f6f4f4";
    
  }
}

var reset = {
  margin: "",
  padding: "",
  position: "absolute",
  boxSizing: "border-box"
};

var Style = 0;

exports.Style = Style;
exports.color = color;
exports.reset = reset;
/* No side effect */
