// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var MyComponent$Workshop = require("./MyComponent.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, MyComponent$Workshop.make("Hello!", /* array */[])), "app");

/*  Not a pure module */
