// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Style$Workshop = require("./Style.bs.js");
var Button$Workshop = require("./Button.bs.js");

var component = ReasonReact.statelessComponent("NavBar");

function make(rootNode, nextButton, prevButton, onNext, onPrev, _, _$1) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", {
                          style: Style$Workshop.project(rootNode, Style$Workshop.zIndex(100, Style$Workshop.reset))
                        }, ReasonReact.element(undefined, undefined, Button$Workshop.make(nextButton[/* node */0], /* Info */2, onNext, /* array */[nextButton[/* text */1]])), ReasonReact.element(undefined, undefined, Button$Workshop.make(prevButton[/* node */0], /* Secondary */1, onPrev, /* array */[prevButton[/* text */1]])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var S = 0;

exports.S = S;
exports.component = component;
exports.make = make;
/* component Not a pure module */
