// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Style$Workshop = require("./Style.bs.js");

function str(prim) {
  return prim;
}

function style(palette) {
  return ReactDOMRe.Style[/* combine */0](Style$Workshop.palette(palette), {
              fontSize: "48px",
              textAlign: "center"
            });
}

function a(palette, href, text) {
  return React.createElement("a", {
              style: ReactDOMRe.Style[/* combine */0](Style$Workshop.palette(palette), {
                    display: "block",
                    padding: "30px",
                    textDecoration: "none"
                  }),
              href: href
            }, text);
}

var Common = /* module */[
  /* style */style,
  /* a */a
];

function Make(B) {
  var component = ReasonReact.statelessComponent(B[/* name */0]);
  var make = function (node, _) {
    return /* record */[
            /* debugName */component[/* debugName */0],
            /* reactClassInternal */component[/* reactClassInternal */1],
            /* handedOffState */component[/* handedOffState */2],
            /* willReceiveProps */component[/* willReceiveProps */3],
            /* didMount */component[/* didMount */4],
            /* didUpdate */component[/* didUpdate */5],
            /* willUnmount */component[/* willUnmount */6],
            /* willUpdate */component[/* willUpdate */7],
            /* shouldUpdate */component[/* shouldUpdate */8],
            /* render */(function () {
                return React.createElement("section", {
                            style: Style$Workshop.project(node, style(B[/* theme */1]))
                          }, B[/* body */2]);
              }),
            /* initialState */component[/* initialState */10],
            /* retainedProps */component[/* retainedProps */11],
            /* reducer */component[/* reducer */12],
            /* jsElementWrapped */component[/* jsElementWrapped */13]
          ];
  };
  return /* module */[
          /* component */component,
          /* make */make
        ];
}

var body = React.createElement("fragment", undefined, React.createElement("h1", undefined, "Welcome to the Reason Workshop! 🎉"), React.createElement("p", undefined, a(/* Primary */0, "https://github.com/ostera", "👤 @ostera"), a(/* Primary */0, "https://go/toolbox", "👥 #content-toolbox"), a(/* Primary */0, "https://github.com/ReasonSTHLM", "🗣 #reasonml"), a(/* Primary */0, "https://meetup.com/ReasonSTHLM", "🗓 ReasonSTHLM Meetup")));

var component = ReasonReact.statelessComponent("Slide.Intro");

function make(node, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("section", {
                          style: Style$Workshop.project(node, style(/* Primary */0))
                        }, body);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var Intro = /* module */[
  /* component */component,
  /* make */make
];

var body$1 = React.createElement("fragment", undefined, React.createElement("h1", undefined, "Let\'s get our hands dirty"), React.createElement("p", undefined, "Setup and Intro"), React.createElement("p", undefined, "What is Reason?"), React.createElement("p", undefined, "A sample app"), React.createElement("p", undefined, "ReasonReact"), React.createElement("p", undefined, "State of the Ecosystem"));

var component$1 = ReasonReact.statelessComponent("Slide.Workshop");

function make$1(node, _) {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */component$1[/* didMount */4],
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("section", {
                          style: Style$Workshop.project(node, style(/* Secondary */1))
                        }, body$1);
            }),
          /* initialState */component$1[/* initialState */10],
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */component$1[/* reducer */12],
          /* jsElementWrapped */component$1[/* jsElementWrapped */13]
        ];
}

var Workshop = /* module */[
  /* component */component$1,
  /* make */make$1
];

var body$2 = React.createElement("fragment", undefined, React.createElement("h1", undefined, "Stay Reasonable 🙌🏼"), React.createElement("p", undefined, "And thanks for coming."), React.createElement("p", undefined, "@ostera"));

var component$2 = ReasonReact.statelessComponent("Slide.Thanks");

function make$2(node, _) {
  return /* record */[
          /* debugName */component$2[/* debugName */0],
          /* reactClassInternal */component$2[/* reactClassInternal */1],
          /* handedOffState */component$2[/* handedOffState */2],
          /* willReceiveProps */component$2[/* willReceiveProps */3],
          /* didMount */component$2[/* didMount */4],
          /* didUpdate */component$2[/* didUpdate */5],
          /* willUnmount */component$2[/* willUnmount */6],
          /* willUpdate */component$2[/* willUpdate */7],
          /* shouldUpdate */component$2[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("section", {
                          style: Style$Workshop.project(node, style(/* Primary */0))
                        }, body$2);
            }),
          /* initialState */component$2[/* initialState */10],
          /* retainedProps */component$2[/* retainedProps */11],
          /* reducer */component$2[/* reducer */12],
          /* jsElementWrapped */component$2[/* jsElementWrapped */13]
        ];
}

var Thanks = /* module */[
  /* component */component$2,
  /* make */make$2
];

var body$3 = React.createElement("fragment", undefined, React.createElement("h1", undefined, "Useful Links"), React.createElement("p", undefined, a(/* Secondary */1, "https://reasonml.github.com", "ReasonML Website"), a(/* Secondary */1, "https://bucklescript.github.io", "BuckleScript Website"), a(/* Primary */0, "https://reasonml.github.io/docs/en/community", "🗣 ReasonML Community")));

var component$3 = ReasonReact.statelessComponent("Slide.Links");

function make$3(node, _) {
  return /* record */[
          /* debugName */component$3[/* debugName */0],
          /* reactClassInternal */component$3[/* reactClassInternal */1],
          /* handedOffState */component$3[/* handedOffState */2],
          /* willReceiveProps */component$3[/* willReceiveProps */3],
          /* didMount */component$3[/* didMount */4],
          /* didUpdate */component$3[/* didUpdate */5],
          /* willUnmount */component$3[/* willUnmount */6],
          /* willUpdate */component$3[/* willUpdate */7],
          /* shouldUpdate */component$3[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("section", {
                          style: Style$Workshop.project(node, style(/* Secondary */1))
                        }, body$3);
            }),
          /* initialState */component$3[/* initialState */10],
          /* retainedProps */component$3[/* retainedProps */11],
          /* reducer */component$3[/* reducer */12],
          /* jsElementWrapped */component$3[/* jsElementWrapped */13]
        ];
}

var Links = /* module */[
  /* component */component$3,
  /* make */make$3
];

var S = 0;

exports.S = S;
exports.str = str;
exports.Common = Common;
exports.Make = Make;
exports.Intro = Intro;
exports.Workshop = Workshop;
exports.Thanks = Thanks;
exports.Links = Links;
/* body Not a pure module */
