// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Yoga = require("@ostera/reiki/lib/js/src/Yoga.bs.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");

function color(param) {
  switch (param) {
    case 0 : 
        return "rgba(0,0,0,0)";
    case 1 : 
        return "#ffffff";
    case 2 : 
        return "#333333";
    case 3 : 
        return "#dd4b39";
    case 4 : 
        return "#37b978";
    case 5 : 
        return "#3f92db";
    case 6 : 
        return "#f6f4f4";
    
  }
}

var reset = {
  left: "0",
  margin: "0",
  outline: "none",
  padding: "0",
  position: "absolute",
  top: "0",
  zIndex: "0",
  boxSizing: "border-box"
};

function zIndex(i, s) {
  return ReactDOMRe.Style[/* combine */0](s, {
              zIndex: String(i)
            });
}

function bgColor(c, s) {
  return ReactDOMRe.Style[/* combine */0](s, {
              backgroundColor: color(c)
            });
}

function textColor(c, s) {
  return ReactDOMRe.Style[/* combine */0](s, {
              color: color(c)
            });
}

function paletteStyle(bg, text, border) {
  return {
          backgroundColor: color(bg),
          borderColor: color(border),
          color: color(text)
        };
}

function palette(param) {
  switch (param) {
    case 0 : 
        return paletteStyle(/* Accent */3, /* White */1, /* Accent */3);
    case 1 : 
        return paletteStyle(/* White */1, /* Accent */3, /* Accent */3);
    case 2 : 
        return paletteStyle(/* Info */5, /* White */1, /* Info */5);
    
  }
}

function project(node, style) {
  var layout = Yoga.Node[/* computedLayout */3](node);
  var top = String(layout[/* top */1]) + "px";
  var left = String(layout[/* left */0]) + "px";
  var width = String(layout[/* width */2]) + "px";
  var height = String(layout[/* height */3]) + "px";
  return ReactDOMRe.Style[/* combine */0](style, {
              height: "" + (String(height) + ""),
              left: "" + (String(left) + ""),
              position: "absolute",
              top: "" + (String(top) + ""),
              width: "" + (String(width) + "")
            });
}

var S = 0;

exports.S = S;
exports.color = color;
exports.reset = reset;
exports.zIndex = zIndex;
exports.bgColor = bgColor;
exports.textColor = textColor;
exports.paletteStyle = paletteStyle;
exports.palette = palette;
exports.project = project;
/* Yoga Not a pure module */
